### ISSUE TITLE
Is there a way to restore saved sessions to browser if Cache was deleted?

### ISSUE THREAD

**Issue by marinlitrenta** [voidlabs/mosaico.io#2]
I accidentally cleared all cookies and cached files from my browser. I still have all of my Mosaico IDs written down and hyperlinked in an excel sheet. Is there anyway to recover the saved sessions?

Hi, I'm trying to help solve this problem of not being to access content on Mosaico.io. The error message reads "app-0.17.5.min.js?v=0.17.5-nr:90 TODO not found  odegs6j Cannot find stored data for odegs6j." How can we gain access to the content ID that was already created? Been working on this for 2 weeks and would not want to start all over again.
thanks for your help, Ron

**Comment by bago** [comment]
I'm sorry, the template structure/content for our demo site mosaico.io is currently ONLY stored in your browser. If you deleted it, you lost it.

**Comment by bago** [comment]
The id is "odegs6j" but it is just a reference to your browser storage content. If you emptied it, the id is useless.
